# Book settings
title: DATA 301
author: Firas Moosvi
logo: images/logo.jpg
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md", "source material","unused/*", "binary files/*"]
only_build_toc_files: true

bibtex_bibfiles:
  - about/citations.bib

latex:
  latex_documents:
    targetname: book.tex
html:
  navbar_number_sections : false
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  google_analytics_id: UA-168693744-4
  baseurl : "https://firas.moosvi.com/courses/2021_ST2/data301"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis: false
    utterances:
      repo: "ubco-cmps/data301_course"
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

launch_buttons:
  notebook_interface : "jupyterlab"
  binderhub_url      : "https://mybinder.org"
  thebe              : true

repository: 
  url          : https://github.com/ubco-cmps/data301_course
  path_to_book : ""
  branch       : main

sphinx:
  extra_extensions:
    - sphinx_thebe
  config:
    html_show_copyright: false
    html_extra_path: ['files']
    bibtex_reference_style: author_year
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - substitution
    myst_substitutions:
      INSTRUCTOR: "Dr. Firas Moosvi (he/his/him)"
      PRONOUNCE: "[Fur-az Moose-vee](https://namedrop.io/firasmoosvi)"
      OFFICE: "ROOM 111"
      PHONE: "N/A"
      COURSE_CODE: "DATA 301 or COSC 301"
      SECTION: "001"
      CREDITS: "3"
      TITLE: "Introduction to Data Analytics"
      PREREQS: "Either (a) third-year standing, or (b) one of COSC 111 or COSC 122."
      COREQS: "None"
      TERM: "2021 Summer Term 2"
      ROOM: "Online (Zoom) - Lectures will be recorded and available on Canvas."
      MEETING_TIMES: "Tuesday, Wednesday, and Friday from 12-2:30 PM"
      GRACE_PERIOD: "48 hour"
      W_DATE_1: "July 9, 2021 11:59 PDT"
      W_DATE_2: "August 6, 2021 11:59 PDT"
      W_DATE_3: "11:59 PDT on August 6, 2021"
      EXAM_PERIOD: "Monday August 16th - Friday, August 20th"
      CANVAS_ID: "71816"
      CANVAS_LINK: "https://canvas.ubc.ca/courses/CANVAS_ID"
      ZOOM_LINK: "[Zoom](https://canvas.ubc.ca/courses/CANVAS_ID/external_tools/15408)"
      ANNOUNCEMENTS_LINK: "[Canvas Announcements](https://canvas.ubc.ca/courses/CANVAS_ID/announcements)"
      COURSE_LINK: "https://firas.moosvi.com/courses/2021_ST2/data301"
      # FORUM_LINK: "[Ed Discussion](https://edstem.org/us/join/H9z4gh)"
      FORUM_LINK: "[Ed Discussion (sign up for it here)](https://ubc.ca1.qualtrics.com/jfe/form/SV_1BTAIXiMPvBRR2K)"
      ANALYTICS_OPTOUT: "[complete this form](https://ubc.ca1.qualtrics.com/jfe/form/SV_0p6lP4TtNpJn410)"
      FORMAT: "Lectures and Labs and they will all be running online in this course."
      ASSOCIATE_HEAD: "Yves Lucet [yves.lucet@ubc.ca](mailto:yves.lucet@ubc.ca)"
      ANON_FEEDBACK: "[feedback form](https://ubc.ca1.qualtrics.com/jfe/form/SV_6FhZZZAe9WoKdnv)"
