# Book settings
title: DATA 301
author: Firas Moosvi & Patricia Lasserre
logo: images/logo.jpg
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md", "source material","notes/05Databases.ipynb", "notes/06Python.ipynb", "notes/07Python.ipynb","binary files/*", "notes/11Visualization.ipynb"]

latex:
  latex_documents:
    targetname: book.tex
html:
  navbar_number_sections : false
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  google_analytics_id: UA-168693744-4
  baseurl : "https://firas.moosvi.com/courses/data301/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis: true
    utterances:
      repo: "ubco-cmps/data301_course"
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

launch_buttons:
  notebook_interface : "jupyterlab"
  binderhub_url      : "https://mybinder.org"
  thebe              : true

repository: 
  url          : https://github.com/ubco-cmps/data301_course
  path_to_book : ""
  branch       : master

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['files']
  extra_extensions:
    - sphinx_thebe
parse:
  myst_extended_syntax: true